@startuml
'https://plantuml.com/component-diagram

package Forntend{
    component WebFrontend
    component Mobile
}

package Backend{
component WebAPI
component NyhetService
component KursService

database MySQLDatabase
}

WebFrontend --> WebAPI
Mobile --> WebAPI

WebAPI --> NyhetService
WebAPI --> KursService

NyhetService --> MySQLDatabase
KursService --> MySQLDatabase


@enduml